### ISSUE TITLE
Error HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by jhomarolo** [ninosaurus/eslint-check#19]
I am creating an action according to the documentation and I have this error. Can someone tell me why?

```
Run ninosaurus/eslint-check@v5
Error HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/ninosaurus/eslint-check/v5/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createCheck (/home/runner/work/_actions/ninosaurus/eslint-check/v5/dist/github.js:24:7)
    at async run (/home/runner/work/_actions/ninosaurus/eslint-check/v5/dist/index.js:73:14)
##[error]Resource not accessible by integration
```

My action:

```
    - name: Run ESLint
      uses: ninosaurus/eslint-check@v5
      with:
        eslint-config-path: "./.eslintrc.json"
        custom-directory: "./src"
        repo-token: ${{secrets.GITHUB_TOKEN}}

```

**Comment by marceaupatu123** [comment]
Same for me
